version: '3'

services:
  redis:
    container_name: redaudioapi-redis
    hostname: redaudioapi-redis
    command: ["--appendonly", "yes",
              "--maxmemory", "2g",
              "--maxmemory-policy","allkeys-lru",
              "--loadmodule", "/usr/lib/redis/modules/redisai.so",
              "--loadmodule", "/usr/lib/redis/modules/redisearch.so",
              "--loadmodule", "/usr/lib/redis/modules/redisgraph.so",
              "--loadmodule", "/usr/lib/redis/modules/redistimeseries.so",
              "--loadmodule", "/usr/lib/redis/modules/rejson.so",
              "--loadmodule", "/usr/lib/redis/modules/redisbloom.so",
              "--loadmodule", "/var/opt/redislabs/lib/modules/redisgears.so",
              "PythonHomeDir", "/opt/redislabs/lib/modules/python3"]
    env_file:
      - .env
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.2
    image: redislabs/redismod
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  postgres:
    container_name: redaudioapi-postgres
    hostname: redaudioapi-postgres
    image: postgres:12.0
    env_file:
      - .env
    volumes:
      - redaudioapi-pgdata:/var/lib/postgresql/data # Run `docker volume create --name=redaudioapi-pgdata`
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.3
    restart: unless-stopped

  pgadmin:
    container_name: redaudioapi-pgadmin
    hostname: redaudioapi-pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.4
    restart: unless-stopped

  api:
    container_name: redaudioapi-api
    hostname: redaudioapi-api
    image: drapersniper/redbot-global-api:latest
#    image: test
    env_file:
      - .env
    environment:
      RED_API_DATABASE: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@redaudioapi-postgres/${POSTGRES_DB}
      REDIS_CACHED_DATA: redis://redaudioapi-redis
      ES_CLUSTER: 172.40.0.7:9200
    networks:
      default:
      redaudioapi-net:
        ipv4_address: 172.40.0.5
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    links:
      - redis
      - postgres
      - es03

  pgbackup:
    container_name: redaudioapi-pgbackup
    hostname: redaudioapi-pgbackup
    image: kartoza/pg-backup:9.6
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./data/backups:/backups
    links:
      - postgres:postgres
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.6
    environment:
      - POSTGRES_HOST=redaudioapi-postgres

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: redaudioapi-es01
    hostname: redaudioapi-es01
    environment:
      - node.name=redaudioapi-es01
      - cluster.name=es-redaudioapi-es-cluster
      - discovery.seed_hosts=redaudioapi-es02,redaudioapi-es03
      - cluster.initial_master_nodes=redaudioapi-es01,redaudioapi-es02,redaudioapi-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - postgres
      - redis
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - redaudioapies01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.7
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: redaudioapi-es02
    hostname: redaudioapi-es02
    environment:
      node.name=redaudioapi-es02
      - cluster.name=es-redaudioapi-es-cluster
      - discovery.seed_hosts=redaudioapi-es01,redaudioapi-es03
      - cluster.initial_master_nodes=redaudioapi-es01,redaudioapi-es02,redaudioapi-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - redaudioapies02:/usr/share/elasticsearch/data
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.8
    depends_on:
      - es01
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: redaudioapi-es03
    hostname: redaudioapi-es03
    environment:
      - node.name=redaudioapi-es02
      - cluster.name=es-redaudioapi-es-cluster
      - discovery.seed_hosts=redaudioapi-es01,redaudioapi-es02
      - cluster.initial_master_nodes=redaudioapi-es01,redaudioapi-es02,redaudioapi-es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - redaudioapies03:/usr/share/elasticsearch/data
    networks:
      redaudioapi-net:
        ipv4_address: 172.40.0.9
    depends_on:
      - es02

networks:
  redaudioapi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16

volumes:
  redaudioapi-pgdata:
    external: true
  redaudioapies01:
    driver: local
  redaudioapies02:
    driver: local
  redaudioapies03:
    driver: local
